### ISSUE TITLE
View run-time exception due to bad namespace in views Web.config

### ISSUE THREAD

**Issue by jasonbert** [LaubPlusCo/LaubPlusCo.Helix.VsTemplates#1]
The `Views\Web.config` contains a namespace called `code`. This causes a run-time exception as the namespace doesn't exist.

https://github.com/LaubPlusCo/LaubPlusCo.Helix.VsTemplates/blob/2cf9454dbbfd7a9168bbf7024040f2138c1da634/StandardTemplates/HabitatStyle.Feature.Module/src/Feature/%24modulename%24/code/Views/web.config#L19

**Comment by anderslaub** [comment]
namespace was removed from built-in templates. To update the extracted templates, click reinstall built in templates from settings dialog.
