### ISSUE TITLE
Projects being created are NOT web projects

### ISSUE THREAD

**Issue by GoranHalvarsson** [LaubPlusCo/LaubPlusCo.Helix.VsTemplates#10]
Noticed that projects being created are standard c# lib projects. That means no help adding razor view, controllers etc.
![Issue](https://user-images.githubusercontent.com/726479/54472485-65987680-47c9-11e9-8e0c-b727bff0f8a4.png)

**Comment by bakgaard** [comment]
You can modify the templates yourself, adding folders for Controllers/Views/ViewModels/Models, and adding files. Perhaps some dependency injection as well.

Then again, if you go with JSS, you have other requirements, so a 'one size fits all' is hard to make.

**Comment by GoranHalvarsson** [comment]
I have to disagree... How many will go for JSS...

Sure you can add all sort of stuff, folders and all that. But, you don’t have the option to select controllers or razor views(when selecting add new item). What I'm trying to say, it will be hard to use. And I want to use it, so how can we fix that? :)

**Comment by GoranHalvarsson** [comment]
Im glad you answered :)

**Comment by anderslaub** [comment]
@GoranHalvarsson thanks for feedback. Easy to just change ProjectTypeGuid if you miss these short links - see response here https://github.com/LaubPlusCo/helix-msbuild-example/issues/1

**Comment by anderslaub** [comment]
I thought I had a quick hack for this which I hadn't tried out yet.

But I just read a MS blog stating that this hack is highly discouraged so - sorry, new project format should not be mixed with the old project types so no hack anyway.

You can add item templates to Visual Studio's context menus, toolbars, etc. in numerous ways anyway; Just look in Options. The quick links just doesn't come ootb based on project type (yet at least) as it did with the old Web Application project type.

**Comment by GoranHalvarsson** [comment]
Hello @anderslaub 
Could you please show how to add templates to Visual Studio's context menus. I looked in Options but could not find anything, I must be dumb :). Would be great if you could show an example of how to do it
