### ISSUE TITLE
Incorrect Helix Template root folder displayed in Settings dialog

### ISSUE THREAD

**Issue by tonycwang** [LaubPlusCo/LaubPlusCo.Helix.VsTemplates#18]
ISSUE:
 when a .helixtemplates file is used in a solution and the templates.modules.folder value is set, it is not reflected in the settings dialog in Visual Studio.

EXPECTED BEHAVIOR:
 when a .helixtemplates file is used, the path specified in templates.modules.folder should be the path shown in the template. otherwise, it should be the global value set when no .helixtempaltes file exists in the solution folder.

**Comment by anderslaub** [comment]
The path shown in the settings dialog is the "global" template folder path. This global folder is required for solution templates. For module templates you can edit the path in the .helixtemplates settings file in the solution root.

It should be made more clear in the UI and perhaps we should also enable editing of the solution scope .helixtemplates settings file from the settings dialog. I will try to include this in upcoming release.

**Comment by anderslaub** [comment]
The new version that is up for release today has an extra tab in the settings dialog for solution scope settings.

The implementation is a bit rudimentary for now, have to draw a line somewhere to ever get anything done :) It works though, feedback is as always highly appreciated.

**Comment by anderslaub** [comment]
This has been released to VS marketplace today (better late than never :)
