### ISSUE TITLE
Microsoft.AspNetCore.Mvc Missing Assembly Reference

### ISSUE THREAD

**Issue by vincent-kong** [LaubPlusCo/LaubPlusCo.Helix.VsTemplates#19]
When opening a CSHTML View file in Visual Studio, I seem to be getting the following error:

> The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) 

The project seems to build fine and is auto-publishing.

This can be replicated on the Helix.Msbuild.Example project (https://github.com/LaubPlusCo/helix-msbuild-example) that utilises the templates.

We are currently have the following set-up:
- Visual Studio 2019
- Helix Template v0.9.9.14

**Comment by anderslaub** [comment]
This is really just Visual Studio's Intellisense that is making false assumptions about your target framework and not real errors.

In your "Error List" window you can select "Build only" from a drop-down and then you won't see them anymore. 

I have not yet found a real way to get VS Intellisense to behave correct for "old" mvc .cshtml files in a sdk project - it must be possible somehow but I haven't had time to investigate it further - and really need for it. Razor view intellisense in Visual Studio has never been perfect.
