### ISSUE TITLE
Website Template is not configured for VS to recognize it as a MVC project

### ISSUE THREAD

**Issue by tonycwang** [LaubPlusCo/LaubPlusCo.Helix.VsTemplates#21]
When using the Website project template, the resulting project that is created is not recognized by Visual Studio as an MVC project.  As such, options for razor views, controllers, etc. are not available.

**Comment by JoeyNovais** [comment]
Do you have a quick fix for this ?

**Comment by anderslaub** [comment]
The microsoft.net.sdk projects are not MVC projects so this is not really an error.

You can create / configure item templates in Visual Studio for your project/solution if you miss these old built-in MVC templates. 

I personally just use "Add >>New Empty file" for views, configs etc. and "Add >> Class..." for classes.
