### ISSUE TITLE
Sitecore 9.3

### ISSUE THREAD

**Issue by sziencik** [LaubPlusCo/LaubPlusCo.Helix.VsTemplates#24]
I am a bit confused how to change from 9.1 to 9.3.  I have changed the version number in the dialog but after generation 9.1.0 still referenced.  I have had to manually update references on every new project added.  I would appreciate some clarification.

Thanks.

**Comment by anderslaub** [comment]
In the new release that I am making public today, the example templates targets 9.3.

I have also detached the templates from the extension so they can be updated separately from the settings dialog. See this repo here https://github.com/LaubPlusCo/Helix-Templates - many more template examples will be added and you are very welcome to make pull requests with new ones.
