### ISSUE TITLE
Error: This template attempted to load component assembly 'LaubPlusCo.VisualStudio.Helix.Wizard, Version=1.0.0.0

### ISSUE THREAD

**Issue by Amir818** [LaubPlusCo/LaubPlusCo.Helix.VsTemplates#34]
After updating the version (uninstalled, and resinstalled), I get the following error after you click the "Create" button in VS:

![image](https://user-images.githubusercontent.com/6593239/97353652-881dbd00-1851-11eb-9f30-ea3ffbee1462.png)

**Comment by anderslaub** [comment]
Fixed and update pushed to VS Market Place.

If this issue occur, try to uninstall the extension and then install it again.
