### ISSUE TITLE
Item publish from TDS project

### ISSUE THREAD

**Issue by MahanthShashanth** [LaubPlusCo/LaubPlusCo.Helix.VsTemplates#38]
Hello,

I have setup the TDS project for all the layers. But when i build solution, items which are added or modified are not getting updated in Sitecore instance. I am trying to see if there is any step/task which will sync the items in Sitecore through MSBuild.

**Comment by anderslaub** [comment]
Hi,

This is not related to the template Visual Studio extension. 

If you'd like to propose or contribute changes to the example templates, please use this repository - https://github.com/LaubPlusCo/Helix-Templates

Thanks.

--Anders
