### ISSUE TITLE
Unit tests fails to run in any project inside Helix solution

### ISSUE THREAD

**Issue by sumanbaul** [LaubPlusCo/LaubPlusCo.Helix.VsTemplates#39]
My project solution is based on Sitecore Helix Visual Studio Templates by Ander's Laub. Im trying to write Unit tests using XUnit, but none of the tests are running and not even failing.

For test projects, I have tried using Project based on Class Library(.NET Framework), Projects based on Sitecore Helix Visual Studio Templates by Ander's Laub.

Packages used:

XUnit(2.4.1)
XUnit.Runner.VisualStudio(2.4.3)
XUnit.Runner.Console(2.4.1)
Framework: .NET 4.8

Visual Studio 2019: v16.8.5

The output im getting:
![image](https://user-images.githubusercontent.com/14125003/116379493-ada37780-a830-11eb-81b7-fe58bd9baeb7.png)

Test Run Output window:

```
ProjectData: Could not find project with GUID 09fe023c-998c-4a4c-a896-bc27884e7aaf
ProjectData: Could not find project with GUID 09fe023c-998c-4a4c-a896-bc27884e7aaf
---------- Starting test run ----------
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.3+1b45f5407b (64-bit Desktop .NET 4.0.30319.42000)
No test matches the given testcase filter `FullyQualifiedName=Linde.Foundation.SitecoreExtensions.Tests.DemoTests.DemoTestForPassingOnly` in C:\SourceTree\lindemh-sitecore\bin\Debug\Linde.Foundation.SitecoreExtensions.Tests.dll
========== Test run finished: 0 Tests run in 1.3 sec (0 Passed, 0 Failed, 0 Skipped) ==========
```

I have tried building a separate Console Application with Tests project to make sure whether this is a Visual Studio Issue, but it is running/failing/passing inside the console application, but not inside the Sitecore Project.

Do I have to configure the solution differently in order for the Tests to run successfully?

**Comment by pbakun** [comment]
I'm using [helix-msbuild-example](https://github.com/LaubPlusCo/helix-msbuild-example) and also struggling with that. I have a feeling that same fix will work for both of us. Did you manage to find solution for test project to run? 

I have same as yours message in Tests output when try to execute tests in Test Explorer.

If I try using `dotnet test` I get:

```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
No test is available in E:\git\DXP-platform\bin\website\Debug\RICC.DXP.Feature.CustomComponents.Tests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

Additionally, path to test adapters can be specified using /TestAdapterPath command. Example  /TestAdapterPath:<pathToCustomAdapters>.
```

**Comment by anderslaub** [comment]
This is not a bug in the extension but some error in your project files.
