### ISSUE TITLE
Helix Templates for VS2022

### ISSUE THREAD

**Issue by GoranHalvarsson** [LaubPlusCo/LaubPlusCo.Helix.VsTemplates#40]
Great tool :-)

Will you update the template so it can be installed on VS2022

**Comment by anderslaub** [comment]
Thank you.

Yes, an update of the extension to VS2022 is already in the works. It'll be released soon.

**Comment by ThomasLohr** [comment]
Yes, to an update of the extension, fantastic news @anderslaub :). Cheers

**Comment by anderslaub** [comment]
@ThomasLohr and @GoranHalvarsson I've just released the extension to Visual Studio Marketplace with VS 2022 support.

Please let me know if you encounter issues. There are also some new simple example templates for Sitecore 10.2 using AspNet RenderingHost.

**Comment by GoranHalvarsson** [comment]
Wonderful 😄
Well done !!

**Comment by ThomasLohr** [comment]
fantastic news :). Great work, will do!
