### ISSUE TITLE
Can't create new project un VS2015

### ISSUE THREAD

**Issue by fnass** [LaubPlusCo/LaubPlusCo.Helix.VsTemplates#5]
Hi @anderslaub,

Tried to use Sitecore Helix Visual Studio Templates Version 0.9.9.3 to create new project in VS2015 but I got this issue 

> could not load assembly Laubplusco.Visual studio.HelixTemplates.Dialogs one or more dependency

![image](https://user-images.githubusercontent.com/40604165/41919066-eacbcaae-795d-11e8-976c-6399bc122649.png)

It works fine in VS2017 but we still working in some projects VS2015.

I have an old version Sitecore Helix Visual Studio Templates 0.9.9.1 and it works fine in VS2015

Can you help us to fix this issue?

Thanks in advance

**Comment by anderslaub** [comment]
VS 2015 is no longer officially supported due to VS API changes - it has been removed from the extension manifest a while back.
